basePath: /v1
definitions:
  models.CreateStudent:
    properties:
      email:
        type: string
      first_name:
        maxLength: 30
        minLength: 2
        type: string
      last_name:
        maxLength: 30
        minLength: 2
        type: string
      phone_number:
        type: string
      username:
        maxLength: 30
        minLength: 2
        type: string
    required:
    - email
    - first_name
    - last_name
    - phone_number
    - username
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.GetAllResponse:
    properties:
      count:
        type: integer
      students:
        items:
          $ref: '#/definitions/models.Student'
        type: array
    type: object
  models.ResponseOK:
    properties:
      message:
        type: string
    type: object
  models.Student:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        maxLength: 30
        minLength: 2
        type: string
      id:
        type: integer
      last_name:
        maxLength: 30
        minLength: 2
        type: string
      phone_number:
        type: string
      username:
        maxLength: 30
        minLength: 2
        type: string
    required:
    - email
    - first_name
    - last_name
    - phone_number
    - username
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a blog service api.
  title: Swagger for blog api
  version: "1.0"
paths:
  /students:
    get:
      consumes:
      - application/json
      description: Get all students
      parameters:
      - default: 10
        in: query
        name: limit
        required: true
        type: integer
      - default: 1
        in: query
        name: page
        required: true
        type: integer
      - in: query
        name: search
        type: string
      - enum:
        - asc
        - desc
        - none
        in: query
        name: sort_by_date
        required: true
        type: string
      - enum:
        - asc
        - desc
        - none
        in: query
        name: sort_by_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetAllResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all students
      tags:
      - students
    post:
      consumes:
      - application/json
      description: Create a student
      parameters:
      - description: student
        in: body
        name: student
        required: true
        schema:
          items:
            $ref: '#/definitions/models.CreateStudent'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ResponseOK'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a student
      tags:
      - students
swagger: "2.0"
